repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes]
    -   id: ruff-format
-   repo: https://github.com/samueljsb/sort-lines
    rev: v0.3.0
    hooks:
    -   id: sort-lines
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: ['-p', '.*[^0-9a-z-_/.=].*']
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-mock-methods
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        additional_dependencies: ['django<5.0', 'django-stubs', 'pytest', 'types-python-dateutil']
